### ISSUE TITLE
Create New ToDo List

### ISSUE THREAD

**Issue by darian29** [darian29/todo#8]
When the user clicks the +, display a Modal that have: 
- [ ]  List Name Input Box
- [ ]  Create Button with primary colors
- [ ] When the user clicks create, add the new list object to the users data in localstorage
